In [1]:
import pandas as pd
import scipy
import random
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
stop_words = stopwords.words('english')
from langdetect import detect
import re, string
#from gensim.models.doc2vec import Doc2Vec
#from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import torch.autograd as autograd         # computation graph
from torch import Tensor 
import torch# tensor node in the computation graph
import torch.nn as nn                     # neural networks
import torch.nn.functional as F           # layers, activations and more
import torch.optim as optim   

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
tw_df = pd.read_csv("Twitter_Data.csv")
red_df = pd.read_csv("Reddit_Data.csv")

In [3]:
tw_df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [4]:
red_df.head()

clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [5]:
red_df.dropna(inplace = True, how = "any")
tw_df.dropna(inplace = True, how = "any")

In [6]:
data_list = []
for i, row in red_df.iterrows():
    data_list.append((row["clean_comment"].split(),row["category"]))
for i, row in tw_df.iterrows():
    data_list.append((row["clean_text"].split(),row["category"]))

In [7]:
data_list.append(("Hier steht einfach mal was deutsches".split(),0))

In [8]:
lemmatizer = WordNetLemmatizer()
data = []
for i,(text,klasse) in enumerate(data_list):
    try:
        if len(text)>1 and detect(" ".join(text)) == "en" :
            text = [lemmatizer.lemmatize(word.lower()) for word in text if word not in stop_words]
        
            data.append((text,klasse))
        else:
            pass
            #print(text)
    except:
        print(text)

['️️️️️️️️️️️️️️️', '️️️️️️️️️️️️️️', '️️️️️️️️️️️', '️️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️', '️️️️️️️', '️️️️️️️️️', '️️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️️', '️️️️', '️️️️️️️️', '️️️️️️️️️️️️️️️']
['༼', '◕\\', '◕', '༽']
['⌚1145', '❤']
['▬▬▬◙▬▬▬', '═▂▄▄▓▄▄▂', '◢◤', '█▀▀████▄▄▄▄◢◤', '█▄', '█', '█▄', '███▀▀▀▀▀▀▀╬', '◥█████◤', '══╩══╩═', '╬═╬', '╬═╬', '╬═╬', '╬═╬', '╬═╬', '╬═╬☻', '╬═╬▌', '╬═╬', '\\', 'just', 'dropped', 'down', '╬═╬', 'say', 'aayega', 'modi']
['\u2066', '\u2066', '\u2066', '\u2066', '\u2066', '\u2066']
['’', '’']


In [13]:
import copy
save_data = copy.deepcopy(data)

In [15]:
for i, (text,value) in enumerate(data):
    for k in text:
        if len(k)<=2:
            text.remove(k)
    data[i]= (text,value)

In [9]:
len(data)

182851

In [10]:
len(data_list)

200119

In [16]:
data[-1]

(['ever',
  'listen',
  'like',
  'gurukul',
  'discipline',
  'maintained',
  'even',
  'narendra',
  'modi',
  'maintaining',
  'culture',
  'indian',
  'attack',
  'politics',
  'someone',
  'attack',
  'hinduism',
  'take',
  'action',
  'proud'],
 1.0)

In [17]:
dic = {}
for i, (text,value) in enumerate(data):
    dic[i] = (text,value)

In [20]:
import json
with open("data.json", "w") as f:
    json.dump(dic,f)

# Ab hier mit importierten Daten

In [2]:
import pandas as pd
import scipy
import random
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
stop_words = stopwords.words('english')
from langdetect import detect
import re, string
#from gensim.models.doc2vec import Doc2Vec
#from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import torch.autograd as autograd         # computation graph
from torch import Tensor 
import torch# tensor node in the computation graph
import torch.nn as nn                     # neural networks
import torch.nn.functional as F           # layers, activations and more
import torch.optim as optim   
import json

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [28]:
with open("data.json", "r") as f:
    data = json.load(f)

In [4]:
tfidf_vectorizer = TfidfVectorizer()

In [5]:
descriptions_representation_tfidf = tfidf_vectorizer.fit_transform([" ".join(text) for text, klasse in data.values()])

In [9]:
descriptions_representation_tfidf.shape

(182851, 115859)

In [10]:

scipy.sparse.isspmatrix(descriptions_representation_tfidf[0])

True

In [11]:
data_rep = scipy.sparse.csr_matrix.toarray(descriptions_representation_tfidf)

In [12]:
rep_list = list()

for i in range(data_rep.shape[0]):
    
    rep = data_rep[i]
    klasse = data[str(i)][1]
    rep_list.append((rep, klasse))

In [13]:
random.shuffle(rep_list)

In [14]:
train_ = rep_list[:int(len(rep_list)*0.6)]
test_ = rep_list[int(len(rep_list)*0.6):int(len(rep_list)*0.7)]

In [91]:
device = torch.device('cpu' if not torch.cuda.is_available() else 'cuda')
def create_batches(liste, batch_size = 64, num_classes = 3):
    
    batches = list()
    batch = list()
    
    targets = list()
    target = list()
    
    for i, (d, t) in enumerate(liste, start = 1):
        if i % batch_size == 0:
            
            label = np.zeros(num_classes)
            t_ = 2 if t == -1 else int(t)
            label[t_] = 1
            label = torch.from_numpy(label).to(device)
            target.append(label)
            target = torch.stack(target)
            targets.append(target)
            
            d = torch.from_numpy(np.array(d)).to(device)
            #batch.append(d)
            batch.append(d.to(device))
            
            batch = torch.stack(batch)
            batches.append(batch)
            
            batch = list()
            target = list()
            
        else:
            d = torch.from_numpy(np.array(d)).to(device)
            #batch.append(d)
            
            batch.append(d.to(device))
            
            label = np.zeros(num_classes)
            t_ = 2 if t == -1 else int(t)
            label[t_] = 1
            
            label = torch.from_numpy(label).to(device)
            target.append(label)
    if len(batch) > 0:
        label = np.zeros(num_classes)
        t_ = 2 if t == -1 else int(t)
        label[t_] = 1
        label = torch.from_numpy(label).to(device)
        target.append(label)
        target = torch.stack(target)
        targets.append(target)
        
        d = torch.from_numpy(np.array(d)).to(device)
        batch.append(d)
        
        batch = torch.stack(batch)
        batches.append(batch)
    return batches, targets
            


In [92]:
train_batches, train_targets = create_batches(embedding_list[:1800])
test_batches, test_targets = create_batches(embedding_list[1800:], batch_size = 1)

In [17]:
len(train_targets[2])

64

In [18]:
len(train_batches[0])

64

In [19]:
#test_batches, test_targets = create_batches(test_, batch_size = 1)

In [20]:
train_batches[0].shape

torch.Size([64, 115859])

In [21]:
len(train_targets[2])

64

In [22]:
train_targets[1].shape

torch.Size([64, 3])

In [23]:
len(train_batches)

1714

# ELMO

In [138]:
import tensorflow as tf
import tensorflow_hub as hub
from keras.layers import Lambda
from keras.models import Input
from keras import backend as K
import time
import dask

import argparse
import numpy as np
import copy
import torch
from scipy.spatial.distance import cosine
from scipy.spatial import KDTree

from allennlp.commands.elmo import ElmoEmbedder

seed = 0
random.seed(seed)
torch.manual_seed(seed)
np.random.seed(seed)

In [51]:

#parser = argparse.ArgumentParser(
#    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
#parser.add_argument(
#    '--elmo_weights_path',
#    type=str,
#    default='$l_weights.hdf5',
#    help="Path to elmo weights files - use $l as a placeholder for language.")
#parser.add_argument(
#    '--elmo_options_path',
#    type=str,
#    default='options262.json',
#    help="Path to elmo options file. n_characters in the file should be 262")
#parser.add_argument(
#    '--align_path',
#    type=str,
#    default='$l_best_mapping.pth',
#    help="Path to the aligning matrix saved in a pyTorch format. Use $l as a placeholder for language.")
#parser.add_argument(
#    '-l1',
#    '--language1',
#    type=str,
#    default='en',
#    help="language of sentence 1")
#parser.add_argument(
#    '-s1',
#    '--sent1',
#    type=str,
#    default=
#    'A house cat is valued by humans for companionship and for its ability to hunt rodents.',
#    help="sentence in language 1")
#parser.add_argument(
#    '-w1',
#    '--word1',
#    type=str,
#    default='cat',
#    help=
#    "Examined word from the sentence of language 1 (first occurrence will be used)"
#)
#parser.add_argument(
#    '-l2',
#    '--language2',
#    type=str,
#    default='en',
#    help="language of sentence 2")
#parser.add_argument(
#    '-s2',
#    '--sent2',
#    type=str,
#    default=
#    'Hannah smells like a pile of poop and she doesnt seem to care.',
#    help="sentence in language 2")
#parser.add_argument(
#    '-w2',
#    '--word2',
#    type=str,
#    default='poop',
#    help=
#    "Examined word from the sentence of language 2 (first occurrence will be used)"
#)
#parser.add_argument(
#    '--layer', type=int, default=1, help="Layer of Elmo to compute for")
#parser.add_argument(
#    '-c', '--cuda_device', type=int, default=-1, help="Cuda device")
#args = parser.parse_args()


#def parse_config(args):
#    '''
#    Replaces $l for the two languages.
#    Prints the args
#    '''
#
#    new_args = copy.deepcopy(args)
#    for k in vars(args):
#        val = getattr(args, k)
#        if type(val) is str and "$l" in val:
#            new_val = val.replace("$l", args.language1)
#            new_k = "{}_{}".format(k, "l1")
#            setattr(new_args, new_k, new_val)
#
#            new_val = val.replace("$l", args.language2)
#            new_k = "{}_{}".format(k, "l2")
#            setattr(new_args, new_k, new_val)
#
#    print('-' * 30)
#    for k in vars(new_args):
#        print("{}: {}".format(k, getattr(new_args, k)))
#    print('-' * 30)
#
#    return new_args
elmo_options_file = 'options262.json' 
elmo_weights_file = 'en_weights.hdf5'
layer = 1
cuda_device = -1
elmo = ElmoEmbedder(elmo_options_file, elmo_weights_file, cuda_device)


def get_sent_embeds(sent, elmo_options_file, elmo_weights_file, layer,
                    cuda_device):
    '''
    Get the embeddings of the sentence words.
    sent - list of tokens
    elmo_options_file - json for model. n_characters should be 262
    elmo_weights_file - saved model
    layer - what layer of ELMo to output
    cuda_device - cuda device
    returns a numpy array with the embeddings per token for the selected layer
    '''
    #elmo = ElmoEmbedder(elmo_options_file, elmo_weights_file, cuda_device)
    s_embeds = elmo.embed_sentence(sent)
    layer_embeds = s_embeds[layer,:,:]
    return layer_embeds

#def analyze_sents(embeds_l1, embeds_l2, sent1, sent2, w1_ind, w2_ind, k=5):
#    kdt = KDTree(embeds_l1)
#    emb2 = embeds_l2[w2_ind]
#    top_k_inds = kdt.query(emb2, k)[1]
#    top_k_words = [sent1[i] for i in top_k_inds]
#    print('Nearest {} neighbors for {} in "{}":\n{}'.format(k, sent2[w2_ind], ' '.join(sent1), ' ,'.join(top_k_words)))
#
#    emb1 = embeds_l1[w1_ind]
#    dist = cosine(emb1, emb2)
#    print("Cosine distance between {} and {}: {}".format(sent1[w1_ind], sent2[w2_ind],dist))

#if __name__ == '__main__':
    
def elmo_embedding(sent_tokens, language = 'en', elmo_options_path = 'options262.json', 
                   elmo_weights_path_l1 = 'en_weights.hdf5', layer = 1, cuda_device = -1):
    #args = parse_config(args)

    # Language 1
    #assert elmo_weights_path_l1.split('_')[0] == language, 'model weights need to be in given language!'
    #sent_tokens = sentence.strip().split()
    #w1_ind = sent1_tokens.index(args.word1)
    s_embeds = elmo.embed_sentence(sent_tokens)
    sent_embeds = s_embeds[layer,:,:]
    #sent_embeds = get_sent_embeds(sent_tokens, elmo_options_path,
    #                            elmo_weights_path_l1, layer,
    #                            cuda_device)
    return sent_embeds
    #align1 = torch.load(args.align_path_l1)
    #s1_embeds_aligned = np.matmul(s1_embeds, align1.transpose())

    # Language 2
    #sent2_tokens = args.sent2.strip().split()
    #w2_ind = sent2_tokens.index(args.word2)
    #s2_embeds = get_sent_embeds(sent2_tokens, args.elmo_options_path,
    #                            args.elmo_weights_path_l2, args.layer,
    #                            args.cuda_device)
#
    #align2 = torch.load(args.align_path_l2)
    #s2_embeds_aligned = np.matmul(s2_embeds, align2.transpose())
#
    ## Analyse
    #print("--- Before alignment:")
    #analyze_sents(s1_embeds, s2_embeds, sent1_tokens, sent2_tokens, w1_ind, w2_ind)
#
    #print("\n--- After alignment:")
    #analyze_sents(s1_embeds_aligned, s2_embeds_aligned, sent1_tokens, sent2_tokens, w1_ind, w2_ind)


In [22]:
test_embeddings = elmo_embedding('Julian is a stupid sock')
print(test_embeddings.shape)
np.mean(test_embeddings).shape

(5, 1024)


(5120,)

In [27]:
np.mean(test_embeddings, axis = 0).reshape(1,1024).shape

(1, 1024)

In [29]:
with open("data.json", "r") as f:
    data = json.load(f)

In [80]:
def create_elmo_embeddings(data, input_dim = 1024):
    data_reps = list()
    #data_classes = list()
    for i, (text, klasse) in data.items():
        #rep = elmo_embedding(' '.join(text))
        rep = dask.delayed(elmo_embedding)(text)
        rep = np.mean(rep, axis = 0)#.reshape(1,input_dim)#zusammenfassen der embeddings und reshape
        
        data_reps.append((rep, klasse))
        #data_classes.append(klasse)
    return data_reps#, data_classes
    #return data_reps
embedding_list = create_elmo_embeddings(data)
random.shuffle(embedding_list)
n = time.time()
print('computing embedding results')
embedding_list = [(emb.compute(),klasse) for emb, klasse in embedding_list[:2000]]
print(time.time() -n, 'secs')

computing embedding results
800.9620780944824 secs


In [76]:
new = list()
for emb in embedding_list:
    n = time.time()
    emb = emb.compute()
    new.append(emb)
    print(time.time()-n)

0.6454720497131348
2.885606288909912
1.1007401943206787
0.3708019256591797
1.5795199871063232
0.35289502143859863
2.231818914413452
1.2372331619262695
0.4387960433959961
1.1774992942810059
0.20851922035217285
1.1925230026245117
1.4118788242340088
0.7426021099090576
0.16595768928527832
1.0963618755340576
0.5344409942626953
0.14202189445495605
0.8294799327850342
1.236137866973877
0.27056217193603516
0.9658660888671875
1.4288232326507568
0.30411601066589355
1.271726131439209
0.12928104400634766
0.3401908874511719
0.18036818504333496
0.24474596977233887
1.4123759269714355
1.362541913986206
0.3973822593688965


KeyboardInterrupt: 

In [70]:
embedding_list = [emb.compute() for emb in embedding_list]

In [71]:
embedding_list

[array([ 0.4031878 ,  0.16243467,  0.12477823, ...,  0.2283159 ,
         1.5754666 , -0.2954133 ], dtype=float32)]

In [67]:
def compute_dask(emb):
    return emb.compute()

In [66]:
n = time.time()
embedding_list[0][0].compute().shape
print(time.time()-n, 'sec')

0.6534740924835205 sec


In [36]:
len(data)

182851

In [73]:
182851*0.0003

54.85529999999999

In [77]:
1000/60

16.666666666666668

In [81]:
embedding_list

[(array([ 0.6399638 ,  0.09948287,  0.04617299, ...,  0.07224528,
          1.244455  , -0.23515368], dtype=float32),
  -1.0),
 (array([ 0.1542456 ,  0.2447226 ,  0.12987472, ..., -0.00224901,
          1.4847941 , -0.410032  ], dtype=float32),
  -1.0),
 (array([ 0.56607807,  0.22879644,  0.07960453, ...,  0.17779723,
          1.5114682 , -0.5201056 ], dtype=float32),
  -1.0),
 (array([ 0.17267473,  0.06613524,  0.658028  , ...,  0.10513069,
          1.291897  , -0.34561488], dtype=float32),
  0.0),
 (array([ 0.64905   , -0.00220925,  0.24639076, ...,  0.11102328,
          1.7674361 , -0.48279107], dtype=float32),
  -1.0),
 (array([ 0.07667167,  0.30090326,  0.4417537 , ...,  0.03012747,
          0.766082  , -0.6305099 ], dtype=float32),
  0.0),
 (array([ 0.7980192 ,  0.19908859, -0.16809778, ...,  0.01336341,
          1.2968259 , -0.36127418], dtype=float32),
  -1.0),
 (array([ 0.23591378,  0.1304848 ,  0.14450438, ...,  0.27536863,
          1.5332392 , -0.5213866 ], dtype=float

In [172]:
class Sentiment(nn.Module):
    
    def __init__(self, input_dim):
        super(Sentiment, self).__init__()
        
        self.input_layer = nn.Linear(input_dim, 750)
        
        #skip connection blocks mit dim 500
        self.hidden_layer0_0 = nn.Linear(750, 500)
        self.hidden_layer0_1 = nn.Linear(500, 500)
        
        self.hidden_layer0_2 = nn.Linear(500, 500)
        self.hidden_layer0_3 = nn.Linear(500, 500)
        
        self.hidden_layer0_4 = nn.Linear(500, 500)
        self.hidden_layer0_5 = nn.Linear(500, 500)
        
        self.hidden_layer0_6 = nn.Linear(500, 500)
        self.hidden_layer0_7 = nn.Linear(500, 500)
        
        #skip connection blocks mit dim 350
        self.hidden_layer1_0 = nn.Linear(500, 350)
        self.hidden_layer1_1 = nn.Linear(350, 350)
        
        self.hidden_layer1_2 = nn.Linear(350, 350)
        self.hidden_layer1_3 = nn.Linear(350, 350)
        
        self.hidden_layer1_4 = nn.Linear(350, 350)
        self.hidden_layer1_5 = nn.Linear(350, 350)
        
        self.hidden_layer1_6 = nn.Linear(350, 350)
        self.hidden_layer1_7 = nn.Linear(350, 350)
        
        #skip connection blocks mit dim 200
        self.hidden_layer2_0 = nn.Linear(350, 200)
        self.hidden_layer2_1 = nn.Linear(200, 200)
        
        self.hidden_layer2_2 = nn.Linear(200, 200)
        self.hidden_layer2_3 = nn.Linear(200, 200)
        
        self.hidden_layer2_4 = nn.Linear(200, 200)
        self.hidden_layer2_5 = nn.Linear(200, 200)
        
        self.hidden_layer2_6 = nn.Linear(200, 200)
        self.hidden_layer2_7 = nn.Linear(200, 200)
        
        #skip connection blocks mit dim 75
        self.hidden_layer3_0 = nn.Linear(200, 75)
        self.hidden_layer3_1 = nn.Linear(75, 75)
        
        self.hidden_layer3_2 = nn.Linear(75, 75)
        self.hidden_layer3_3 = nn.Linear(75, 75)
        
        self.hidden_layer3_4 = nn.Linear(75, 75)
        self.hidden_layer3_5 = nn.Linear(75, 75)
        
        self.hidden_layer3_6 = nn.Linear(75, 75)
        self.hidden_layer3_7 = nn.Linear(75, 75)
        
        #skip connection blocks mit dim 3
        #self.hidden_layer4_0 = nn.Linear(75, 3)
        #self.hidden_layer4_1 = nn.Linear(3, 3)
        #
        #self.hidden_layer4_2 = nn.Linear(3, 3)
        #self.hidden_layer4_3 = nn.Linear(3, 3)
        #
        #self.hidden_layer4_4 = nn.Linear(3, 3)
        #self.hidden_layer4_5 = nn.Linear(3, 3)
        #
        #self.hidden_layer4_6 = nn.Linear(3, 3)
        #self.hidden_layer4_7 = nn.Linear(3, 3)
        
        #"normale" linear layer
        #self.hidden_layer1 = nn.Linear(500, 350)
        #self.hidden_layer2 = nn.Linear(350, 200)
        #self.hidden_layer3 = nn.Linear(200, 75)
        self.output_layer = nn.Linear(75, 3)
        
    def create_block(input_dim = 500):
        pass 
        
    def forward(self,x):
        x = F.relu(self.input_layer(x.float()))#x dim 750
        
        #skip connections mit dim 500
        #block 0
        out_0 = F.relu(self.hidden_layer0_0(x))#out dim 500
        x = F.relu(self.hidden_layer0_1(out_0))#layer das im zweifel geskipped werden kann, x dim = 500
        
        #block 1 ...
        out_1 = F.relu(self.hidden_layer0_2(x) + out_0)#x dim 500, out dim 500
        x = F.relu(self.hidden_layer0_3(out_1))
        
        out_2 = F.relu(self.hidden_layer0_2(x) + out_1)#x dim 500, out dim 500
        x = F.relu(self.hidden_layer0_3(out_2))
        
        out_3 = F.relu(self.hidden_layer0_2(x) + out_2)#x dim 500
        x = F.relu(self.hidden_layer0_3(out_3))
        
        #skip connections mit dim 350
        #block 0
        out_0 = F.relu(self.hidden_layer1_0(x))#out dim 500
        x = F.relu(self.hidden_layer1_1(out_0))#layer das im zweifel geskipped werden kann, x dim = 500
        
        #block 1 ...
        out_1 = F.relu(self.hidden_layer1_2(x) + out_0)#x dim 500
        x = F.relu(self.hidden_layer1_3(out_1))
        
        out_2 = F.relu(self.hidden_layer1_2(x) + out_1)#x dim 500
        x = F.relu(self.hidden_layer1_3(out_2))
        
        out_3 = F.relu(self.hidden_layer1_2(x) + out_2)#x dim 500
        x = F.relu(self.hidden_layer1_3(out_3))
        
        #skip connections mit dim 200
        #block 0
        out_0 = F.relu(self.hidden_layer2_0(x))#out dim 500
        x = F.relu(self.hidden_layer2_1(out_0))#layer das im zweifel geskipped werden kann, x dim = 500
        
        #block 1 ...
        out_1 = F.relu(self.hidden_layer2_2(x) + out_0)#x dim 500
        x = F.relu(self.hidden_layer2_3(out_1))
        
        out_2 = F.relu(self.hidden_layer2_2(x) + out_1)#x dim 500
        x = F.relu(self.hidden_layer2_3(out_2))
        
        out_3 = F.relu(self.hidden_layer2_2(x) + out_2)#x dim 500
        x = F.relu(self.hidden_layer2_3(out_3))
        
        #skip connections mit dim 75
        #block 0
        out_0 = F.relu(self.hidden_layer3_0(x))#out dim 500
        x = F.relu(self.hidden_layer3_1(out_0))#layer das im zweifel geskipped werden kann, x dim = 500
        
        #block 1 ...
        out_1 = F.relu(self.hidden_layer3_2(x) + out_0)#x dim 500
        x = F.relu(self.hidden_layer3_3(out_1))
        
        out_2 = F.relu(self.hidden_layer3_2(x) + out_1)#x dim 500
        x = F.relu(self.hidden_layer3_3(out_2))
        
        out_3 = F.relu(self.hidden_layer3_2(x) + out_2)#x dim 500
        x = F.relu(self.hidden_layer3_3(out_3))
        
        #skip connections mit dim 3
        #block 0
        #out_0 = F.relu(self.hidden_layer4_0(x))#out dim 500
        #x = F.relu(self.hidden_layer4_1(out_0))#layer das im zweifel geskipped werden kann, x dim = 500
        #
        ##block 1 ...
        #out_1 = F.relu(self.hidden_layer4_2(x) + out_0)#x dim 500
        #x = F.relu(self.hidden_layer4_3(out_1))
        #
        #out_2 = F.relu(self.hidden_layer4_2(x) + out_1)#x dim 500
        #x = F.relu(self.hidden_layer4_3(out_2))
        #
        #out_3 = F.relu(self.hidden_layer4_2(x)+ out_2)#x dim 500
        #x = F.softmax(self.hidden_layer4_3(out_3))
        
        #x = F.relu(self.hidden_layer1(x + out_3))
        #x = F.relu(self.hidden_layer2(x))
        #x = F.relu(self.hidden_layer3(x))
        x = F.softmax(self.output_layer(x))#vorher nur x
        return x
    
def train(mse = True):
    model.train()
    train_loss = 0
    for batch_id, batch in enumerate(train_batches):
        target = train_targets[batch_id].float()
        
        optimizer.zero_grad()
        if mse:
            out = model(batch).float()
            loss = criterion(out, target).float()
        else:
            out = model(batch).float()
            '''
            HIER nochmal dringend ändern, weil falsch denke ich (nicht auf target bezogen)
            '''
            loss = criterion(out, torch.max(target, 1)[1].long())#.long()
        
        train_loss += loss.item()
        
        loss.backward()
        optimizer.step()
        
    return train_loss/len(train_batches)
        
        
def test():
    model.eval()
    correctly_classified = 0
    
    with torch.no_grad():
    
        for batch_id, batch in enumerate(test_batches):
            target = test_targets[batch_id].float()
            
            
            out = model(batch).float()
            
            out = torch.argmax(out)
            tar = torch.argmax(target)
            
            if out == tar:
                correctly_classified += 1
                
    return correctly_classified/len(test_batches)

In [159]:
loss_df = pd.DataFrame(columns = ['epoche', 'loss', 'accuracy'])
model = Sentiment(1024).float()
optimizer = optim.Adam(model.parameters(), lr = 0.00005)
criterion = nn.MSELoss()
for e in range(100):
    #print(e +1)
    loss_ = train()
    acc = test()
    if (e+1)%5 == 0:
        print(f"Epoche: {e+1}, Accuracy: {acc}, Trainloss: {loss_}")
    loss_df.loc[len(loss_df),:] = [e+1, loss_, acc]

/Users/juliangreil/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:163: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


KeyboardInterrupt: 

#### Lossfunktion von MSE zu Crossentropy ändern

In [174]:
loss_df = pd.DataFrame(columns = ['epoche', 'loss', 'accuracy'])
model = Sentiment(1024).float()
optimizer = optim.Adam(model.parameters(), lr = 0.001)
criterion = nn.NLLLoss()#nn.CrossEntropyLoss()
for e in range(100):
    #print(e +1)
    loss_ = train(mse=False)
    acc = test()
    if (e+1)%5 == 0:
        print(f"Epoche: {e+1}, Accuracy: {acc}, Trainloss: {loss_}")
    loss_df.loc[len(loss_df),:] = [e+1, loss_, acc]

/Users/juliangreil/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:163: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


Epoche: 5, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 10, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 15, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 20, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 25, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 30, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 35, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 40, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 45, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 50, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 55, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 60, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 65, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 70, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 75, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 80, Accuracy: 0.405, Trainloss: -0.469647989190858
Epoche: 85, Accuracy: 0.405, Trainloss: -0.46964798919085

In [171]:
torch.FloatTensor(2).uniform_(0, 3).long()

tensor([1, 0])

In [142]:
for name, param in model.named_parameters():
    print(param.grad)
    print(param.shape, '\n')

tensor([[ 9.7366e-12,  2.1214e-11,  8.3243e-12,  ...,  5.3237e-12,
          6.8448e-11, -9.3191e-12],
        [ 2.4299e-06, -1.6838e-07,  1.4733e-06,  ...,  2.5903e-06,
          1.0571e-05, -2.3986e-06],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [-1.7222e-22, -6.4984e-23,  1.9950e-23,  ...,  4.4029e-24,
         -4.4389e-22,  1.0942e-22],
        [-5.0206e-11, -3.0423e-11, -3.5617e-11,  ..., -2.8340e-11,
         -1.1897e-10,  1.1364e-11],
        [ 8.4458e-07, -5.8515e-08,  5.1210e-07,  ...,  9.0031e-07,
          3.6743e-06, -8.3368e-07]])
torch.Size([750, 1024]) 

tensor([ 6.1204e-11,  6.2860e-06,  0.0000e+00, -3.0823e-10,  2.1710e-06,
        -8.5815e-11, -1.6803e-19, -1.1167e-08,  6.1722e-06,  1.0542e-11,
         2.4888e-11, -3.6351e-19, -8.8943e-11,  0.0000e+00,  4.0467e-08,
        -1.1473e-06, -2.0787e-07,  4.3627e-07, -7.5505e-06, -1.5790e-05,
        -1.2554e-10,  3.8729e-11, -1.2532e-05, -1.

In [111]:
loss_df

epoche      loss accuracy
0       1  0.212677    0.405
1       2  0.212368    0.405
2       3  0.212029    0.405
3       4  0.212004    0.405
4       5  0.212004    0.405
..    ...       ...      ...
95     96  0.211868    0.405
96     97  0.211865    0.405
97     98  0.211866    0.405
98     99  0.211865    0.405
99    100  0.211865    0.405

[100 rows x 3 columns]

In [51]:
nuller_klasse = 0
einser_klasse = 0
minuseins_klasse = 0

for (text, klasse) in train_:
    if int(klasse) == 0:
        nuller_klasse += 1
    elif int(klasse) == 1:
        einser_klasse += 1
    else:
        minuseins_klasse += 1
        
for (text, klasse) in test_:
    if int(klasse) == 0:
        nuller_klasse += 1
    elif int(klasse) == 1:
        einser_klasse += 1
    else:
        minuseins_klasse += 1

In [55]:
nuller_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.3082151646548693

In [56]:
einser_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.4614398999960936

In [57]:
minuseins_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.23034493534903708

In [16]:
train_targets

[[tensor([1., 0., 0.], dtype=torch.float64)],
 [tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor(