In [1]:
import pandas as pd
import scipy
import random
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
stop_words = stopwords.words('english')
from langdetect import detect
import re, string
#from gensim.models.doc2vec import Doc2Vec
#from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import torch.autograd as autograd         # computation graph
from torch import Tensor 
import torch# tensor node in the computation graph
import torch.nn as nn                     # neural networks
import torch.nn.functional as F           # layers, activations and more
import torch.optim as optim   

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
tw_df = pd.read_csv("Twitter_Data.csv")
red_df = pd.read_csv("Reddit_Data.csv")

In [3]:
tw_df.head()

clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0

In [4]:
red_df.head()

clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [5]:
red_df.dropna(inplace = True, how = "any")
tw_df.dropna(inplace = True, how = "any")

In [6]:
data_list = []
for i, row in red_df.iterrows():
    data_list.append((row["clean_comment"].split(),row["category"]))
for i, row in tw_df.iterrows():
    data_list.append((row["clean_text"].split(),row["category"]))

In [7]:
data_list.append(("Hier steht einfach mal was deutsches".split(),0))

In [8]:
lemmatizer = WordNetLemmatizer()
data = []
for i,(text,klasse) in enumerate(data_list):
    try:
        if len(text)>1 and detect(" ".join(text)) == "en" :
            text = [lemmatizer.lemmatize(word.lower()) for word in text if word not in stop_words]
        
            data.append((text,klasse))
        else:
            pass
            #print(text)
    except:
        print(text)

['️️️️️️️️️️️️️️️', '️️️️️️️️️️️️️️', '️️️️️️️️️️️', '️️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️', '️️️️️️️', '️️️️️️️️️', '️️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️️', '️️️️️️️️️', '️️️️', '️️️️️️️️', '️️️️️️️️️️️️️️️']
['༼', '◕\\', '◕', '༽']
['⌚1145', '❤']
['▬▬▬◙▬▬▬', '═▂▄▄▓▄▄▂', '◢◤', '█▀▀████▄▄▄▄◢◤', '█▄', '█', '█▄', '███▀▀▀▀▀▀▀╬', '◥█████◤', '══╩══╩═', '╬═╬', '╬═╬', '╬═╬', '╬═╬', '╬═╬', '╬═╬☻', '╬═╬▌', '╬═╬', '\\', 'just', 'dropped', 'down', '╬═╬', 'say', 'aayega', 'modi']
['\u2066', '\u2066', '\u2066', '\u2066', '\u2066', '\u2066']
['’', '’']


In [13]:
import copy
save_data = copy.deepcopy(data)

In [15]:
for i, (text,value) in enumerate(data):
    for k in text:
        if len(k)<=2:
            text.remove(k)
    data[i]= (text,value)

In [9]:
len(data)

182851

In [10]:
len(data_list)

200119

In [16]:
data[-1]

(['ever',
  'listen',
  'like',
  'gurukul',
  'discipline',
  'maintained',
  'even',
  'narendra',
  'modi',
  'maintaining',
  'culture',
  'indian',
  'attack',
  'politics',
  'someone',
  'attack',
  'hinduism',
  'take',
  'action',
  'proud'],
 1.0)

In [17]:
dic = {}
for i, (text,value) in enumerate(data):
    dic[i] = (text,value)

In [20]:
import json
with open("data.json", "w") as f:
    json.dump(dic,f)

# Ab hier mit importierten Daten

In [1]:
import pandas as pd
import scipy
import random
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('stopwords')
stop_words = stopwords.words('english')
from langdetect import detect
import re, string
#from gensim.models.doc2vec import Doc2Vec
#from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
import torch.autograd as autograd         # computation graph
from torch import Tensor 
import torch# tensor node in the computation graph
import torch.nn as nn                     # neural networks
import torch.nn.functional as F           # layers, activations and more
import torch.optim as optim   
import json

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/juliangreil/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
with open("data.json", "r") as f:
    data = json.load(f)

In [3]:
tfidf_vectorizer = TfidfVectorizer()

In [4]:
descriptions_representation_tfidf = tfidf_vectorizer.fit_transform([" ".join(text) for text, klasse in data.values()])

In [5]:
descriptions_representation_tfidf.shape

(182851, 115859)

In [6]:

scipy.sparse.isspmatrix(descriptions_representation_tfidf[0])

True

In [7]:
data_rep = scipy.sparse.csr_matrix.toarray(descriptions_representation_tfidf)

In [8]:
rep_list = list()

for i in range(data_rep.shape[0]):
    
    rep = data_rep[i]
    klasse = data[str(i)][1]
    rep_list.append((rep, klasse))

In [9]:
random.shuffle(rep_list)

In [10]:
train_ = rep_list[:int(len(rep_list)*0.6)]
test_ = rep_list[int(len(rep_list)*0.6):int(len(rep_list)*0.7)]

In [11]:
device = torch.device('cpu' if not torch.cuda.is_available() else 'cuda')
def create_batches(liste, batch_size = 64, num_classes = 3):
    
    batches = list()
    batch = list()
    
    targets = list()
    target = list()
    
    for i, (d, t) in enumerate(liste, start = 1):
        if i % batch_size == 0:
            
            label = np.zeros(num_classes)
            t_ = 2 if t == -1 else int(t)
            label[t_] = 1
            label = torch.from_numpy(label).to(device)
            target.append(label)
            target = torch.stack(target)
            targets.append(target)
            
            d = torch.from_numpy(d).to(device)
            batch.append(d)
            
            batch = torch.stack(batch)
            batches.append(batch)
            
            batch = list()
            target = list()
            
        else:
            d = torch.from_numpy(d).to(device)
            batch.append(d)
            
            label = np.zeros(num_classes)
            t_ = 2 if t == -1 else int(t)
            label[t_] = 1
            
            label = torch.from_numpy(label).to(device)
            target.append(label)
    return batches, targets
            


In [12]:
train_batches, train_targets = create_batches(train_)
test_batches, test_targets = create_batches(test_, batch_size = 1)

In [13]:
len(train_targets[2])

64

In [14]:
len(train_batches[0])

64

In [15]:
#test_batches, test_targets = create_batches(test_, batch_size = 1)

In [16]:
train_batches[0].shape

torch.Size([64, 115859])

In [17]:
len(train_targets[2])

64

In [18]:
train_targets[1].shape

torch.Size([64, 3])

In [22]:
len(train_batches)

1714

In [47]:
class Sentiment(nn.Module):
    
    def __init__(self, input_dim):
        super(Sentiment, self).__init__()
        
        self.input_layer = nn.Linear(input_dim, 15)
        self.hidden_layer = nn.Linear(15, 7)
        self.output_layer = nn.Linear(7, 3)
        
    def forward(self,x):
        x = F.relu(self.input_layer(x.float()))
        x = F.relu(self.hidden_layer(x))
        x = torch.sigmoid(self.output_layer(x))
        return x
    
def train():
    model.train()
    train_loss = 0
    for batch_id, batch in enumerate(train_batches):
        target = train_targets[batch_id].float()
        
        optimizer.zero_grad()
        out = model(batch).float()
        loss = criterion(out, target).float()
        
        train_loss += loss.item()
        
        loss.backward()
        optimizer.step()
        
    return train_loss/len(train_batches)
        
        
def test():
    model.eval()
    correctly_classified = 0
    
    with torch.no_grad():
    
        for batch_id, batch in enumerate(test_batches):
            target = test_targets[batch_id].float()
            
            
            out = model(batch).float()
            
            out = torch.argmax(out)
            tar = torch.argmax(target)
            
            if out == tar:
                correctly_classified += 1
                
    return correctly_classified/len(test_batches)

In [58]:
loss_df = pd.DataFrame(columns = ['epoche', 'loss', 'accuracy'])
model = Sentiment(115859).float()
optimizer = optim.Adam(model.parameters(), lr = 0.001)
criterion = nn.MSELoss()
for e in range(15):
    print(e +1)
    loss_ = train()
    acc = test()
    loss_df.loc[len(loss_df),:] = [e+1, loss_, acc]

1


/Users/juliangreil/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1639: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [59]:
loss_df

epoche        loss  accuracy
0       1    0.146168   0.85819
1       2   0.0522252  0.876511
2       3   0.0357491  0.871972
3       4   0.0277267  0.866831
4       5   0.0226002  0.859885
5       6   0.0191279  0.855018
6       7   0.0166865  0.849877
7       8   0.0149775  0.847307
8       9   0.0136265  0.842822
9      10   0.0126369  0.840361
10     11   0.0119399  0.836861
11     12   0.0114022  0.833908
12     13   0.0107139  0.833634
13     14   0.0101168  0.830681
14     15  0.00953939  0.828986

In [51]:
nuller_klasse = 0
einser_klasse = 0
minuseins_klasse = 0

for (text, klasse) in train_:
    if int(klasse) == 0:
        nuller_klasse += 1
    elif int(klasse) == 1:
        einser_klasse += 1
    else:
        minuseins_klasse += 1
        
for (text, klasse) in test_:
    if int(klasse) == 0:
        nuller_klasse += 1
    elif int(klasse) == 1:
        einser_klasse += 1
    else:
        minuseins_klasse += 1

In [55]:
nuller_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.3082151646548693

In [56]:
einser_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.4614398999960936

In [57]:
minuseins_klasse / (minuseins_klasse+nuller_klasse+einser_klasse)

0.23034493534903708

In [16]:
train_targets

[[tensor([1., 0., 0.], dtype=torch.float64)],
 [tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([1., 0., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor([0., 1., 0.], dtype=torch.float64),
  tensor([0., 0., 1.], dtype=torch.float64),
  tensor(